<div class="container-fluid">

<a class="btn btn-success" type="button" href="<?= base_url('user/tambahprodi') ?>" class="text-white">+ Tambah</a>

<div class="card mt-2">

    <div class="card-body">

        <h4 class="d-flex justify-content-center align-items-center mt-3"><?= $title ?></h4>
        <div class="table-responsive mt-2">
            <table class="table table-borderless" style="color:black;">
                <tr>
                    <td width="200px">Jurusan</td>
                    <td width="10px">:</td>
                    <td>JTPI</td>
                </tr>

                <tr>
                    <td>Strata</td>
                    <td>:</td>
                    <td>S1</td>
                </tr>

                <tr>
                    <td>Universitas</td>
                    <td>:</td>
                    <td>INSTITUT TEKNOLOGI SUMATERA</td>
                </tr>

                <tr>
                    <td>Ruang Lingkup DE</td>
                    <td>:</td>
                    <td>Kompetensi Lulusan</td>
                </tr>

                <tr>
                    <td>Auditor</td>
                    <td>:</td>
                    <td>Tim Auditor Mutu Internal ITERA</td>
                </tr>

                <tr>
                    <td>Tanggal DE</td>
                    <td>:</td>
                    <td></td>
                </tr>

                <tr>
                    <td>Dokumen Acuan</td>
                    <td>:</td>
                    <td>Standar Pengelolaan Pembelajaran</td>
                </tr>
            </table>
        </div>

        <div class="table-responsive">
            <table class="table table-bordered">
                <thead class="text-center">
                    <tr>
                        <th rowspan="2" style="background-color: #808080; color:black;">No</th>
                        <th rowspan="2" style="background-color: #808080; color:black;">Dokumen Terkait</th>
                        <th colspan="4" style="background-color: #ffa07a; color:black;">Kondisi Dokumen</th>
                        <th colspan="2" style="background-color: #3EB489; color:black;">Kategori Temuan</th>
                        <th colspan="2" style="background-color: #B0C4DE; color:black;">Status Temuan</th>
                        <th rowspan="2" style="background-color: #FF8C00; color:black;">Catatan</th>
                        <th rowspan="2" style="background-color: #FFFF00; color:black;">Penanggung Jawab</th>
                    </tr>

                    <tr>
                        <th style="background-color: #ffa07a; color:black;">M*</th>
                        <th style="background-color: #ffa07a; color:black;">MP*</th>
                        <th style="background-color: #ffa07a; color:black;">MB*</th>
                        <th style="background-color: #ffa07a; color:black;">MY*</th>
                        <th style="background-color: #3EB489; color:black;">OB*</th>
                        <th style="background-color: #3EB489; color:black;">KTS*</th>
                        <th style="background-color: #B0C4DE; color:black;">OPEN</th>
                        <th style="background-color: #B0C4DE; color:black;">CLOSE</th>
                    </tr>
                </thead>

                <tbody style="background-color: white; color:black;">
                    <tr>
                        <td>1</td>
                        <td>Tindak Lanjut AMI</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>2</td>
                        <td>Dokumen SOP pelaksanaan Ujian Semester</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>3</td>
                        <td>Dokumen SOP Penilaian perkuliahan paralel</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>4</td>
                        <td>Dokumen SOP Stadium Generale/Seminar Ilmiah</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>5</td>
                        <td>Dokumen SOP Monitoring/Pedoman Tugas Akhir</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>6</td>
                        <td>Dokumen SOP ujian/ sidang tugas akhir</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td ></td>
                    </tr>

                    <tr>
                        <td>7</td>
                        <td>Dokumen rekap Lulusan mahasiswa tiap tahun dan tiap prodi mencakup (IPK, lama studi)</td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td class="text-center"><input type="checkbox" value="1"></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
</div>

<div class="d-flex justify-content-end">
  <button type="submit" class="btn btn-success" name="submit" id="submit">Simpan</button>
  </div>

</div>

<p style="color:black;"> * M= Memenuhi, MP= Melampaui, MB= Belum Memenuhi, MY= Menyimpang <br> <br>* OB= Observasi, KTS= Ketidaksesuaian</br></br></p>


        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end mt-2">
                <li class="page-item">
                    <a class="page-link" href="<?= base_url('auditorjurusan/DaftarHadir') ?>">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="<?= base_url('auditorjurusan/dth2') ?>">Next</a>
                </li>
            </ul>
        </nav>
    </div>

</div>